SELECT DISTINCT ramqID, MOTHER.name
FROM MOTHER
INNER JOIN COUPLE ON MOTHER.ramqID = COUPLE.motherramqID
INNER JOIN PREGNANCY ON PREGNANCY.coupleID = COUPLE.coupleID
INNER JOIN BABY ON BABY.pregnancyID = PREGNANCY.pregnancyID
WHERE (SELECT COUNT(*) FROM BABY WHERE BABY.pregnancyID = PREGNANCY.pregnancyID) > 1;
