insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('ghorrell0@imageshack.us', '947 Crest Line Terrace', '747-542-5435', 'Blanda LLC', 'diigo.com');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('abondy1@google.pl', '07 Linden Terrace', '520-849-5716', 'Mayert, Hoeger and Mertz', 'youtube.com');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('kstoves2@sohu.com', '615 Chinook Alley', '379-545-6973', 'Daugherty, Rau and Kautzer', 'clickbank.net');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('mszachniewicz3@spiegel.de', '78360 Holmberg Lane', '204-313-1220', 'Murazik-Dietrich', 'mozilla.org');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('mdrury4@archive.org', null, null, null, null);
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('mwelbeck5@wordpress.org', '18 Brown Terrace', '316-787-0127', 'Dickinson-Graham', 'dedecms.com');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('amoseby6@free.fr', '78 Truax Center', '836-416-5336', 'Johnston Inc', 'ted.com');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('tgerald7@umn.edu', '4 Westend Road', '498-858-4137', 'Rohan-Bernier', 'omniture.com');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('vdoy8@acquirethisname.com', '91917 Loftsgordon Parkway', '269-808-0647', 'Mitchell LLC', 'tripadvisor.com');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('cwilsey9@nature.com', '95 Scott Circle', '215-141-0247', 'Kautzer, Grimes and Schmidt', 'smugmug.com');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('glarimera@cdbaby.com', '70 Golf Course Junction', '525-314-9025', 'Auer, O''Kon and Kling', 'google.com');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('rtrengrouseb@imgur.com', '4741 Dahle Center', '924-287-1883', 'Zemlak Inc', 'baidu.com');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('dplampinc@edublogs.org', '7187 Kipling Point', '870-392-2742', 'Tillman LLC', 'toplist.cz');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('ebugged@toplist.cz', null, null, null, null);
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('mdelgardilloe@free.fr', '160 Eagle Crest Avenue', '698-192-8400', 'Adams, Gerlach and Zieme', 'loc.gov');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('atornf@nih.gov', '0 Westport Road', '563-605-9087', 'DuBuque-Pollich', 'quantcast.com');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('thassang@friendfeed.com', '193 International Parkway', '165-935-3371', 'Hilpert, Greenholt and Gleichner', 'loc.gov');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('hayrtonh@unblog.fr', '2 Arapahoe Drive', '375-277-9602', 'Hagenes Group', 'archive.org');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('wjirasi@devhub.com', '253 Hanson Plaza', '355-874-9530', 'Herman, Mohr and Runolfsson', 'homestead.com');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('ktuerenaj@vinaora.com', '507 Sachtjen Trail', '210-825-5494', 'Rath-Hettinger', 'accuweather.com');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('tpeacherk@google.it', '8547 Lunder Avenue', '225-641-3499', 'Nader, Sanford and Jones', 'state.gov');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('achasel@house.gov', '8008 Burning Wood Center', '117-468-7760', 'McCullough and Sons', 'feedburner.com');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('kchopym@ed.gov', '845 Springs Terrace', '679-237-6180', 'Rodriguez Group', 'un.org');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('kjerremsn@amazonaws.com', '92126 Trailsway Street', '409-300-0370', 'Bosco Inc', 'slate.com');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('kgreensiteo@tamu.edu', '6922 Crowley Avenue', '114-745-2415', 'Huels, Harber and Champlin', 'e-recht24.de');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('jgoodierp@ameblo.jp', '4666 Parkside Terrace', '672-343-2085', 'Simonis-O''Keefe', 'yahoo.com');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('ndonanq@delicious.com', '6440 Di Loreto Center', '675-809-1364', 'Stoltenberg-Bashirian', 'purevolume.com');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('sfriesr@dropbox.com', '0 Huxley Alley', '752-723-6966', 'Howe LLC', 'theguardian.com');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('tdownss@berkeley.edu', '2 Memorial Center', '184-551-5623', 'Bayer, Schoen and Hand', 'rambler.ru');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('vlevayt@plala.or.jp', '5474 International Park', '702-555-9948', 'Kovacek-Nader', 'alexa.com');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('hbroaderu@mail.ru', '509 4th Avenue', '601-638-1826', 'Robel, Dickens and Walter', 'domainmarket.com');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('lmortlockv@theguardian.com', '4 Gulseth Terrace', '208-439-2860', 'Lockman, Bednar and Schoen', 'wiley.com');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('bdecortw@wsj.com', '2551 Sutteridge Trail', '238-356-4483', 'Gutmann, Treutel and Wisoky', 'geocities.jp');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('hcorkishx@craigslist.org', '2 Wayridge Lane', '742-201-6311', 'Rempel and Sons', 'stanford.edu');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('sbonsally@blinklist.com', '7 David Crossing', '100-691-8861', 'Bahringer, Larson and Cummerata', 'facebook.com');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('earnalz@hostgator.com', '1 Sullivan Center', '742-800-8380', 'Walker, Johnson and Schaefer', 'odnoklassniki.ru');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('ogiffard10@nydailynews.com', '84 Straubel Plaza', '469-988-5487', 'Gutmann, Brakus and Cremin', 'wsj.com');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('jwylie11@va.gov', '12 Walton Trail', '878-684-6736', 'O''Conner-Hand', 'skyrock.com');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('clord12@nba.com', '77058 Scoville Circle', '688-167-7074', 'Stokes Group', 'wisc.edu');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('gemor13@github.io', '26383 Lakewood Drive', '239-981-3567', 'Rosenbaum, Brown and Wehner', 'sphinn.com');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('vpaling14@mac.com', '39 Tomscot Point', '934-655-0769', 'Rohan, Streich and Mosciski', 'vkontakte.ru');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('fbratten15@vinaora.com', '625 Muir Avenue', '337-112-3401', 'Casper and Sons', 'github.com');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('clegassick16@huffingtonpost.com', '3817 Westend Center', '608-311-3064', 'Rempel-Gerlach', 'ning.com');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('rhighman17@illinois.edu', '2 Sunfield Junction', '638-416-5186', 'Rowe-Abbott', 'purevolume.com');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('kedland18@craigslist.org', '1 Sullivan Street', '600-645-2220', 'Stanton and Sons', 'pagesperso-orange.fr');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('chuxham19@infoseek.co.jp', '231 Merchant Junction', '723-390-3050', 'Hettinger-Crona', 'domainmarket.com');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('rjorgesen1a@smugmug.com', '62609 Bultman Pass', '972-713-5010', 'Koelpin-Bradtke', 'wsj.com');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('sbartens1b@ask.com', '6550 Valley Edge Point', '600-822-6942', 'Spencer-Fadel', 'tiny.cc');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('nletteresse1c@cafepress.com', '982 Bartillon Park', '499-913-3227', 'Bauch-Lakin', 'amazonaws.com');
insert into HEALTHINSTITUTION (email, address, phonenum, name, website) values ('twestwell1d@linkedin.com', '26557 Ridgeview Place', '767-289-1742', 'Crooks-Yundt', 'nytimes.com');
