insert into MAINMIDWIFE (pregnancyID, midwifeID) values (1, 1);
insert into MAINMIDWIFE (pregnancyID, midwifeID) values (2, 2);
insert into MAINMIDWIFE (pregnancyID, midwifeID) values (3, 3);
insert into MAINMIDWIFE (pregnancyID, midwifeID) values (4, 4);
insert into MAINMIDWIFE (pregnancyID, midwifeID) values (5, 5);
insert into MAINMIDWIFE (pregnancyID, midwifeID) values (6, 6);
insert into MAINMIDWIFE (pregnancyID, midwifeID) values (7, 7);
insert into MAINMIDWIFE (pregnancyID, midwifeID) values (8, 8);
insert into MAINMIDWIFE (pregnancyID, midwifeID) values (9, 9);
insert into MAINMIDWIFE (pregnancyID, midwifeID) values (10, 10);
insert into MAINMIDWIFE (pregnancyID, midwifeID) values (11, 11);
insert into MAINMIDWIFE (pregnancyID, midwifeID) values (12, 12);
insert into MAINMIDWIFE (pregnancyID, midwifeID) values (13, 13);
insert into MAINMIDWIFE (pregnancyID, midwifeID) values (14, 14);
insert into MAINMIDWIFE (pregnancyID, midwifeID) values (15, 15);
insert into MAINMIDWIFE (pregnancyID, midwifeID) values (16, 16);
insert into MAINMIDWIFE (pregnancyID, midwifeID) values (17, 17);
insert into MAINMIDWIFE (pregnancyID, midwifeID) values (18, 18);



insert into BACKUPMIDWIFE (pregnancyID, midwifeID) values (1, 11);
insert into BACKUPMIDWIFE (pregnancyID, midwifeID) values (2, 12);
insert into BACKUPMIDWIFE (pregnancyID, midwifeID) values (3, 13);
insert into BACKUPMIDWIFE (pregnancyID, midwifeID) values (4, 14);
insert into BACKUPMIDWIFE (pregnancyID, midwifeID) values (5, 15);
insert into BACKUPMIDWIFE (pregnancyID, midwifeID) values (6, 16);
insert into BACKUPMIDWIFE (pregnancyID, midwifeID) values (7, 17);
insert into BACKUPMIDWIFE (pregnancyID, midwifeID) values (8, 18);
insert into BACKUPMIDWIFE (pregnancyID, midwifeID) values (9, 19);
insert into BACKUPMIDWIFE (pregnancyID, midwifeID) values (10, 20);
insert into BACKUPMIDWIFE (pregnancyID, midwifeID) values (11, 21);
insert into BACKUPMIDWIFE (pregnancyID, midwifeID) values (12, 22);
insert into BACKUPMIDWIFE (pregnancyID, midwifeID) values (13, 23);
insert into BACKUPMIDWIFE (pregnancyID, midwifeID) values (14, 24);
insert into BACKUPMIDWIFE (pregnancyID, midwifeID) values (15, 25);
insert into BACKUPMIDWIFE (pregnancyID, midwifeID) values (16, 26);
insert into BACKUPMIDWIFE (pregnancyID, midwifeID) values (17, 27);
insert into BACKUPMIDWIFE (pregnancyID, midwifeID) values (18, 28);
