CONNECT TO cs421;

CREATE VIEW MIDWIFEINFO (mpracID, mname, mphone, memail, hname, haddress) AS
(SELECT MIDWIFE.practitionerID, MIDWIFE.name, MIDWIFE.phonenum, MIDWIFE.email, HEALTHINSTITUTION.name, HEALTHINSTITUTION.address FROM MIDWIFE
JOIN HEALTHINSTITUTION ON MIDWIFE.hemail = HEALTHINSTITUTION.email);
