insert into MIDWIFE (practitionerID, hemail, phonenum, name, email) values (1, 'ghorrell0@imageshack.us', '535-904-7909', 'Schowalter-Grant', 'cseedman0@icq.com');
insert into MIDWIFE (practitionerID, hemail, phonenum, name, email) values (2, 'ghorrell0@imageshack.us', '763-430-6279', 'Glover, Weissnat and Bergnaum', 'skennifick1@hc360.com');
insert into MIDWIFE (practitionerID, hemail, phonenum, name, email) values (3, 'ghorrell0@imageshack.us', '293-321-5023', 'Zulauf Group', 'esurcomb2@ox.ac.uk');
insert into MIDWIFE (practitionerID, hemail, phonenum, name, email) values (4, 'ghorrell0@imageshack.us', '636-965-5575', 'Kautzer Inc', 'bmoatt3@tripadvisor.com');
insert into MIDWIFE (practitionerID, hemail, phonenum, name, email) values (5, 'ghorrell0@imageshack.us', '131-149-2535', 'O''Keefe and Sons', 'rmaddison4@pbs.org');
insert into MIDWIFE (practitionerID, hemail, phonenum, name, email) values (6, 'ghorrell0@imageshack.us', '314-522-2917', 'Langosh, Sanford and Howell', 'hsirett5@senate.gov');
insert into MIDWIFE (practitionerID, hemail, phonenum, name, email) values (7, 'ghorrell0@imageshack.us', '235-865-0099', 'Orn-Kautzer', 'jmalt6@sohu.com');
insert into MIDWIFE (practitionerID, hemail, phonenum, name, email) values (8, 'ghorrell0@imageshack.us', '532-559-1719', 'Hammes, Cartwright and Jones', 'cburree7@state.tx.us');
insert into MIDWIFE (practitionerID, hemail, phonenum, name, email) values (9, 'ghorrell0@imageshack.us', '671-166-0195', 'Aufderhar-Fisher', 'rfiler8@cnet.com');
insert into MIDWIFE (practitionerID, hemail, phonenum, name, email) values (10, 'ghorrell0@imageshack.us', '237-785-2269', 'Monahan, Bailey and Ziemann', 'rjeffray9@washingtonpost.com');
insert into MIDWIFE (practitionerID, hemail, phonenum, name, email) values (11, 'clord12@nba.com', '791-788-2861', 'Wolf Group', 'rmaddamsa@engadget.com');
insert into MIDWIFE (practitionerID, hemail, phonenum, name, email) values (12, 'clord12@nba.com', '758-916-5729', 'Adams, Oberbrunner and Gerhold', 'mfortenb@newyorker.com');
insert into MIDWIFE (practitionerID, hemail, phonenum, name, email) values (13, 'clord12@nba.com', '468-972-1229', 'Wisoky, Wuckert and Corkery', 'mengelbrechtc@geocities.jp');
insert into MIDWIFE (practitionerID, hemail, phonenum, name, email) values (14, 'clord12@nba.com', '169-160-2598', 'Stroman, Heller and Mann', 'vwurstd@redcross.org');
insert into MIDWIFE (practitionerID, hemail, phonenum, name, email) values (15, 'clord12@nba.com', '962-152-3241', 'Tremblay Inc', 'asmarte@myspace.com');
insert into MIDWIFE (practitionerID, hemail, phonenum, name, email) values (16, 'clord12@nba.com', '783-473-0608', 'VonRueden-Mayert', 'jbadseyf@disqus.com');
insert into MIDWIFE (practitionerID, hemail, phonenum, name, email) values (17, 'sclord12@nba.com', '975-668-6448', 'Kertzmann-Mertz', 'jwelburng@opensource.org');
insert into MIDWIFE (practitionerID, hemail, phonenum, name, email) values (18, 'clord12@nba.com', '564-921-9870', 'Fisher, Borer and Renner', 'fhatth@adobe.com');
insert into MIDWIFE (practitionerID, hemail, phonenum, name, email) values (19, 'clord12@nba.com', '765-928-6147', 'Harvey Group', 'pwhibleyi@yelp.com');
insert into MIDWIFE (practitionerID, hemail, phonenum, name, email) values (20, 'clord12@nba.com', '895-497-4974', 'Nolan, Flatley and Kautzer', 'kginnj@ifeng.com');
insert into MIDWIFE (practitionerID, hemail, phonenum, name, email) values (21, 'ebugged@toplist.cz', '409-645-9244', 'Kuhic, Haley and Crooks', 'jmanktelowk@reference.com');
insert into MIDWIFE (practitionerID, hemail, phonenum, name, email) values (22, 'ebugged@toplist.cz', '239-147-8515', 'Altenwerth-Volkman', 'aisacssonl@delicious.com');
insert into MIDWIFE (practitionerID, hemail, phonenum, name, email) values (23, 'ebugged@toplist.cz', '791-460-5486', 'Conn, Hansen and Graham', 'pabramm@stumbleupon.com');
insert into MIDWIFE (practitionerID, hemail, phonenum, name, email) values (24, 'ebugged@toplist.cz', '601-321-0805', 'Price Inc', 'jjordinen@mozilla.org');
insert into MIDWIFE (practitionerID, hemail, phonenum, name, email) values (25, 'ebugged@toplist.cz', '797-787-0446', 'Kiehn-Conroy', 'ppinwello@va.gov');
insert into MIDWIFE (practitionerID, hemail, phonenum, name, email) values (26, 'ebugged@toplist.cz', '860-432-0895', 'Carroll Group', 'gloxlyp@google.fr');
insert into MIDWIFE (practitionerID, hemail, phonenum, name, email) values (27, 'ebugged@toplist.cz', '243-127-3117', 'Barton and Sons', 'lasserq@hibu.com');
insert into MIDWIFE (practitionerID, hemail, phonenum, name, email) values (28, 'ebugged@toplist.cz', '710-203-9583', 'Abshire and Sons', 'mhaberghamr@cocolog-nifty.com');
insert into MIDWIFE (practitionerID, hemail, phonenum, name, email) values (29, 'ebugged@toplist.cz', '536-952-5422', 'Hayes, Cole and Price', 'ggrews@walmart.com');
insert into MIDWIFE (practitionerID, hemail, phonenum, name, email) values (30, 'ebugged@toplist.cz', '913-720-6844', 'Casper-VonRueden', 'ysmutht@narod.ru');
